name: QuantumNest CI/CD Pipeline

on:
    push:
        branches: [main, master, develop]
    pull_request:
        branches: [main, master, develop]
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    # =================================================================
    # INFRASTRUCTURE VALIDATION
    # =================================================================

    infrastructure-lint:
        name: Infrastructure Linting
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Terraform Format Check
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.6.0

            - name: Terraform fmt
              run: |
                  cd infrastructure/terraform
                  terraform fmt -check -recursive
              continue-on-error: false

            - name: Install tflint
              run: |
                  curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

            - name: Run tflint
              run: |
                  cd infrastructure/terraform
                  tflint --init
                  tflint --format compact

            - name: Install yamllint
              run: pip install yamllint

            - name: Lint Kubernetes manifests
              run: |
                  yamllint -c infrastructure/kubernetes/.yamllint infrastructure/kubernetes/

            - name: Install kubeval
              run: |
                  wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
                  tar xf kubeval-linux-amd64.tar.gz
                  sudo mv kubeval /usr/local/bin

            - name: Validate Kubernetes manifests
              run: |
                  kubeval --strict --ignore-missing-schemas infrastructure/kubernetes/base/*.yaml

            - name: Install ansible-lint
              run: pip install ansible-lint

            - name: Lint Ansible playbooks
              run: |
                  cd infrastructure/ansible
                  ansible-lint playbooks/ roles/

    terraform-validate:
        name: Terraform Validation
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.6.0

            - name: Terraform Init
              run: |
                  cd infrastructure/terraform
                  terraform init -backend=false

            - name: Terraform Validate
              run: |
                  cd infrastructure/terraform
                  terraform validate

            - name: Install tfsec
              run: |
                  wget -q https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -O /usr/local/bin/tfsec
                  chmod +x /usr/local/bin/tfsec

            - name: Run tfsec
              run: |
                  cd infrastructure/terraform
                  tfsec . --soft-fail

    # =================================================================
    # APPLICATION TESTS
    # =================================================================

    backend-test:
        name: Backend Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.10'
                  cache: 'pip'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
                  if [ -f backend/requirements-dev.txt ]; then pip install -r backend/requirements-dev.txt; fi

            - name: Run linters
              run: |
                  cd backend
                  # Add linting commands here
                  # pylint $(git ls-files '*.py')
                  # flake8 .
                  echo "Linting passed"

            - name: Run tests
              run: |
                  cd backend
                  python -m pytest --cov=. --cov-report=xml --cov-report=html

            - name: Upload coverage
              uses: codecov/codecov-action@v3
              with:
                  files: backend/coverage.xml
                  flags: backend

    blockchain-test:
        name: Blockchain Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'
                  cache-dependency-path: blockchain/package-lock.json

            - name: Install dependencies
              run: |
                  cd blockchain
                  npm ci

            - name: Run linters
              run: |
                  cd blockchain
                  npm run lint

            - name: Run tests
              run: |
                  cd blockchain
                  npm test

            - name: Run coverage
              run: |
                  cd blockchain
                  npm run coverage

    frontend-test:
        name: Frontend Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'
                  cache-dependency-path: frontend/package-lock.json

            - name: Install dependencies
              run: |
                  cd frontend
                  npm ci

            - name: Run linters
              run: |
                  cd frontend
                  npm run lint

            - name: Run tests
              run: |
                  cd frontend
                  npm test -- --coverage --watchAll=false

            - name: Build
              run: |
                  cd frontend
                  npm run build

    # =================================================================
    # SECURITY SCANNING
    # =================================================================

    security-scan:
        name: Security Scanning
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: 'fs'
                  scan-ref: '.'
                  format: 'sarif'
                  output: 'trivy-results.sarif'

            - name: Upload Trivy results to GitHub Security
              uses: github/codeql-action/upload-sarif@v3
              if: always()
              with:
                  sarif_file: 'trivy-results.sarif'

    # =================================================================
    # BUILD AND DEPLOY (only on main/master)
    # =================================================================

    build-and-push:
        name: Build and Push Docker Images
        needs:
            [
                infrastructure-lint,
                terraform-validate,
                backend-test,
                blockchain-test,
                frontend-test,
                security-scan,
            ]
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    deploy-staging:
        name: Deploy to Staging
        needs: build-and-push
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        runs-on: ubuntu-latest
        environment: staging

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-west-2

            - name: Update kubeconfig
              run: |
                  aws eks update-kubeconfig --name quantumnest-staging-cluster --region us-west-2

            - name: Deploy to Kubernetes
              run: |
                  kubectl apply -k infrastructure/kubernetes/environments/staging/

    deploy-production:
        name: Deploy to Production
        needs: build-and-push
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-west-2

            - name: Update kubeconfig
              run: |
                  aws eks update-kubeconfig --name quantumnest-prod-cluster --region us-west-2

            - name: Deploy to Kubernetes
              run: |
                  kubectl apply -k infrastructure/kubernetes/environments/prod/
