apiVersion: v1
kind: ServiceAccount
metadata:
    name: quantumnest-backend-sa
    namespace: quantumnest-prod
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/QuantumNestBackendRole
        kubernetes.io/service-account.name: quantumnest-backend-sa
    labels:
        app.kubernetes.io/name: quantumnest-backend
        app.kubernetes.io/component: service-account
        app.kubernetes.io/part-of: quantumnest-platform
        security.quantumnest.com/data-classification: confidential
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: quantumnest-frontend-sa
    namespace: quantumnest-prod
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/QuantumNestFrontendRole
        kubernetes.io/service-account.name: quantumnest-frontend-sa
    labels:
        app.kubernetes.io/name: quantumnest-frontend
        app.kubernetes.io/component: service-account
        app.kubernetes.io/part-of: quantumnest-platform
        security.quantumnest.com/data-classification: internal
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: quantumnest-database-sa
    namespace: quantumnest-prod
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/QuantumNestDatabaseRole
        kubernetes.io/service-account.name: quantumnest-database-sa
    labels:
        app.kubernetes.io/name: quantumnest-database
        app.kubernetes.io/component: service-account
        app.kubernetes.io/part-of: quantumnest-platform
        security.quantumnest.com/data-classification: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: quantumnest-monitoring-sa
    namespace: quantumnest-monitoring
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/QuantumNestMonitoringRole
        kubernetes.io/service-account.name: quantumnest-monitoring-sa
    labels:
        app.kubernetes.io/name: quantumnest-monitoring
        app.kubernetes.io/component: service-account
        app.kubernetes.io/part-of: quantumnest-platform
        security.quantumnest.com/data-classification: internal
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: quantumnest-security-sa
    namespace: quantumnest-security
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/QuantumNestSecurityRole
        kubernetes.io/service-account.name: quantumnest-security-sa
    labels:
        app.kubernetes.io/name: quantumnest-security
        app.kubernetes.io/component: service-account
        app.kubernetes.io/part-of: quantumnest-platform
        security.quantumnest.com/data-classification: restricted
---
# ClusterRole for backend services
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: quantumnest-backend-role
    labels:
        app.kubernetes.io/name: quantumnest-backend
        app.kubernetes.io/component: rbac
rules:
    - apiGroups: ['']
      resources: ['secrets', 'configmaps']
      verbs: ['get', 'list']
    - apiGroups: ['']
      resources: ['pods']
      verbs: ['get', 'list', 'watch']
    - apiGroups: ['apps']
      resources: ['deployments', 'replicasets']
      verbs: ['get', 'list', 'watch']
---
# ClusterRoleBinding for backend services
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: quantumnest-backend-binding
    labels:
        app.kubernetes.io/name: quantumnest-backend
        app.kubernetes.io/component: rbac
subjects:
    - kind: ServiceAccount
      name: quantumnest-backend-sa
      namespace: quantumnest-prod
roleRef:
    kind: ClusterRole
    name: quantumnest-backend-role
    apiGroup: rbac.authorization.k8s.io
---
# Role for database operations (namespace-scoped)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: quantumnest-prod
    name: quantumnest-database-role
    labels:
        app.kubernetes.io/name: quantumnest-database
        app.kubernetes.io/component: rbac
rules:
    - apiGroups: ['']
      resources: ['secrets']
      verbs: ['get', 'list']
      resourceNames: ['database-credentials', 'database-ssl-certs']
    - apiGroups: ['']
      resources: ['configmaps']
      verbs: ['get', 'list']
      resourceNames: ['database-config']
    - apiGroups: ['']
      resources: ['persistentvolumeclaims']
      verbs: ['get', 'list', 'watch']
---
# RoleBinding for database operations
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: quantumnest-database-binding
    namespace: quantumnest-prod
    labels:
        app.kubernetes.io/name: quantumnest-database
        app.kubernetes.io/component: rbac
subjects:
    - kind: ServiceAccount
      name: quantumnest-database-sa
      namespace: quantumnest-prod
roleRef:
    kind: Role
    name: quantumnest-database-role
    apiGroup: rbac.authorization.k8s.io
