apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quantumnest-redis-pvc
  namespace: quantumnest-prod
  labels:
    app: quantumnest-redis
    tier: cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
