apiVersion: v1
kind: Service
metadata:
  name: quantumnest-redis
  namespace: quantumnest-prod
  labels:
    app: quantumnest-redis
    tier: cache
    app.kubernetes.io/name: quantumnest-redis
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  selector:
    app: quantumnest-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: metrics
      port: 9121
      targetPort: 9121
      protocol: TCP
