apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: vault-backend
    namespace: quantumnest-prod
spec:
    provider:
        vault:
            server: 'https://vault.quantumnest.internal:8200'
            path: 'secret'
            version: 'v2'
            auth:
                kubernetes:
                    mountPath: 'kubernetes'
                    role: 'quantumnest-external-secrets'
                    serviceAccountRef:
                        name: 'external-secrets-sa'
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: database-credentials
    namespace: quantumnest-prod
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: vault-backend
        kind: SecretStore
    target:
        name: database-secret
        creationPolicy: Owner
        template:
            type: Opaque
            data:
                username: '{{ .username }}'
                password: '{{ .password }}'
                host: '{{ .host }}'
                port: '{{ .port }}'
                database: '{{ .database }}'
                ssl_mode: 'require'
    data:
        - secretKey: username
          remoteRef:
              key: database/prod/quantumnest
              property: username
        - secretKey: password
          remoteRef:
              key: database/prod/quantumnest
              property: password
        - secretKey: host
          remoteRef:
              key: database/prod/quantumnest
              property: host
        - secretKey: port
          remoteRef:
              key: database/prod/quantumnest
              property: port
        - secretKey: database
          remoteRef:
              key: database/prod/quantumnest
              property: database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: api-keys
    namespace: quantumnest-prod
spec:
    refreshInterval: 30m
    secretStoreRef:
        name: vault-backend
        kind: SecretStore
    target:
        name: api-keys-secret
        creationPolicy: Owner
        template:
            type: Opaque
            data:
                jwt_secret: '{{ .jwt_secret }}'
                encryption_key: '{{ .encryption_key }}'
                api_key: '{{ .api_key }}'
                webhook_secret: '{{ .webhook_secret }}'
    data:
        - secretKey: jwt_secret
          remoteRef:
              key: app/quantumnest/auth
              property: jwt_secret
        - secretKey: encryption_key
          remoteRef:
              key: app/quantumnest/crypto
              property: encryption_key
        - secretKey: api_key
          remoteRef:
              key: app/quantumnest/external
              property: api_key
        - secretKey: webhook_secret
          remoteRef:
              key: app/quantumnest/webhooks
              property: secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: tls-certificates
    namespace: quantumnest-prod
spec:
    refreshInterval: 24h
    secretStoreRef:
        name: vault-backend
        kind: SecretStore
    target:
        name: tls-secret
        creationPolicy: Owner
        template:
            type: kubernetes.io/tls
            data:
                tls.crt: '{{ .certificate }}'
                tls.key: '{{ .private_key }}'
                ca.crt: '{{ .ca_certificate }}'
    data:
        - secretKey: certificate
          remoteRef:
              key: pki/issue/quantumnest-server
              property: certificate
        - secretKey: private_key
          remoteRef:
              key: pki/issue/quantumnest-server
              property: private_key
        - secretKey: ca_certificate
          remoteRef:
              key: pki/cert/ca
              property: certificate
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
    name: aws-secrets-manager
spec:
    provider:
        aws:
            service: SecretsManager
            region: us-west-2
            auth:
                secretRef:
                    accessKeyID:
                        name: awssm-secret
                        key: access-key
                        namespace: external-secrets-system
                    secretAccessKey:
                        name: awssm-secret
                        key: secret-access-key
                        namespace: external-secrets-system
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: financial-data-keys
    namespace: quantumnest-prod
spec:
    refreshInterval: 6h
    secretStoreRef:
        name: aws-secrets-manager
        kind: ClusterSecretStore
    target:
        name: financial-keys-secret
        creationPolicy: Owner
        template:
            type: Opaque
            data:
                encryption_key: '{{ .encryption_key }}'
                signing_key: '{{ .signing_key }}'
                audit_key: '{{ .audit_key }}'
    data:
        - secretKey: encryption_key
          remoteRef:
              key: quantumnest/financial/encryption
              property: key
        - secretKey: signing_key
          remoteRef:
              key: quantumnest/financial/signing
              property: key
        - secretKey: audit_key
          remoteRef:
              key: quantumnest/financial/audit
              property: key
