---
- name: Install PostgreSQL packages
  ansible.builtin.package:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
      - libpq-dev
    state: present
  become: true

- name: Ensure PostgreSQL is enabled and running
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Configure PostgreSQL
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/14/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: "0640"
  become: true
  notify: reload postgresql

- name: Configure pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: "0640"
  become: true
  notify: reload postgresql
